from building import *

CWD = GetCurrentDir()

objs = Glob('*.c')

@register_library
class LibraryQemuArmInt(Library):
    def config(self):
        self.Append(CPPPATH=[CWD])
        self.CPPPATH = ['$INFRAS']
        self.source = objs
