from building import *

CWD = GetCurrentDir()

objs = Glob('*.c')

@register_library
class LibraryRTT(Library):
    def config(self):
        self.include = '%s/include'%(CWD)
        self.CPPPATH += ['$INFRAS']
        self.source = objs


for sc in Glob('*/SConscript'):
    SConscript(sc)