from building import *

CWD = GetCurrentDir()

objs = Glob('*.c') + Glob('virtio/*.c') + Glob('dev/*.c')


@register_library
class LibraryRTT(Library):
    def config(self):
        self.include = ['%s/include' % (CWD), '%s/virtio' % (CWD)]
        self.CPPPATH += ['$INFRAS']
        self.LIBS += ['Heap', 'Device']
        self.source = objs


for sc in Glob('*/SConscript'):
    SConscript(sc)
